### PR TITLE
Added fuzzers to fuzz extensions.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
I added three more fuzzers to hit the entry points of the extensions. With these we should be able to get a good amount of coverage on the code!

### CODE REVIEW

**Comment by danielaparker** [comment]
Thanks! I can see the value of fuzzers.

Incidentally, I received a notification yesterday form fuzz with the link

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21589

but I am unable to access the link (permission denied). Any suggestions?

**Comment by DavidKorczynski** [comment]
I think the issues is likely to be your account is not set up as a google account? You need to register it as such and then login using that account - the account that you login with should be the email given here: https://github.com/google/oss-fuzz/blob/master/projects/jsoncons/project.yaml

Perhaps this solves it?

**Comment by danielaparker** [comment]
I think I need to use a google account to get full access. Can you change the email address to 

danielaparker@gmail.com

**Comment by DavidKorczynski** [comment]
> I think I need to use a google account to get full access. Can you change the email address to
> 
> [danielaparker@gmail.com](mailto:danielaparker@gmail.com)

Fixed and merged into oss-fuzz!

**Pull request merged**
