### PR TITLE
Migrating OSS-Fuzz content to upstream

### PR DESCRIPTION
**Pull request by DavidKorczynski**
I am starting to move the content we have on the OSS-Fuzz repo into the main jsoncons repo so we don't have to update OSS-Fuzz everytime we change contents in here. This is the first step.

### CODE REVIEW

**Comment by danielaparker** [comment]
Hi David,

Do you know what this one is about?

Issue 21926: jsoncons: Coverage build failure
Reported by ClusterFuzz-External on Thu, Apr 30, 2020, 6:01 AM EDT (4 hours ago) Project Member
link
Code

more_vert
The last 2 builds for jsoncons have been failing.
Build log: https://oss-fuzz-build-logs.storage.googleapis.com/log-36a58e44-6118-4c85-a79c-2f6c0a0ae23a.txt
Build type: coverage

**Comment by DavidKorczynski** [comment]
I think it's related to what it says in the bottom about "if the fuzzer has run yet". 

If you look at the statistics (https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2020-04-23&date_end=2020-04-29&fuzzer=libFuzzer&job=libfuzzer_asan_jsoncons&project=jsoncons) then you can see there are no actual runs of the fuzzer - so it tries to look for testcases produced by a fuzzer that has not run yet so there will be no testcases. You can safely ignore this error.

**Comment by danielaparker** [comment]
I believe all the oss-fuzz issues reported so far have been fixed.

Can you add sanitizers to the project.yaml file? 

sanitizers:
 - address
 - undefined
 - memory

Thanks!

**Comment by DavidKorczynski** [comment]
All of these are already there! The default is to have all of the different sanitisers so we're already good on that front. I have a few minor things to do tomorrow that I will add, but I think then we should be there for ideal integration!

**Comment by danielaparker** [comment]
Great! Thanks.

**Pull request merged**
