### PR TITLE
chore: Enable codeql action

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This action runs GitHub's industry-leading semantic code analysis engine,
CodeQL, against a repository's source code to find security vulnerabilities.

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by danielaparker** [comment]
CodeQL has a complaint, which I don't understand, and off hand I don't think it's right. In the code
```cpp
{
        basic_bigint<Allocator> r;
        divide( divisor, *this, r, false );
        return *this;
}

```
CodeQL complains "May return stack-allocated memory from `r`." Function `divide` returns a quotient and a remainder as output parameters, in this case, we don't need the remainder, so we output it to the temporary value `r`, which destructs when the function returns, as it should. At no time does any memory bound to `r` leak into a return value.

**Comment by naveensrinivasan** [comment]
> CodeQL has a complaint, which I don't understand, and off hand I don't see how it could be right. In the code
> 
> ```c++
> basic_bigint& operator/=( const basic_bigint<Allocator>& divisor )
> {
>         basic_bigint<Allocator> r;
>         divide( divisor, *this, r, false );
>         return *this;
> }
> ```
> 
> CodeQL complains "May return stack-allocated memory from `r`." Function `divide` returns a quotient and a remainder as output parameters, in this case, we don't need the remainder, so we output it to the temporary value `r`, which destructs when the function returns, as it should. At no time does any memory bound to `r` leak into a return value, at least I don't see how.

TBH I don't know.

**Comment by danielaparker** [comment]
> > CodeQL has a complaint, which I don't understand, and off hand I don't see how it could be right. In the code
> > ```c++
> > basic_bigint& operator/=( const basic_bigint<Allocator>& divisor )
> > {
> >         basic_bigint<Allocator> r;
> >         divide( divisor, *this, r, false );
> >         return *this;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > CodeQL complains "May return stack-allocated memory from `r`." Function `divide` returns a quotient and a remainder as output parameters, in this case, we don't need the remainder, so we output it to the temporary value `r`, which destructs when the function returns, as it should. At no time does any memory bound to `r` leak into a return value, at least I don't see how.
> 
> TBH I don't know.

I note that it's only reporting one issue. Does CodeQL stop at the first issue it finds, or is that the only issue that it's found? 

Thanks,
Daniel

**Comment by naveensrinivasan** [comment]
> > > CodeQL has a complaint, which I don't understand, and off hand I don't see how it could be right. In the code
> > > ```c++
> > > basic_bigint& operator/=( const basic_bigint<Allocator>& divisor )
> > > {
> > >         basic_bigint<Allocator> r;
> > >         divide( divisor, *this, r, false );
> > >         return *this;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > CodeQL complains "May return stack-allocated memory from `r`." Function `divide` returns a quotient and a remainder as output parameters, in this case, we don't need the remainder, so we output it to the temporary value `r`, which destructs when the function returns, as it should. At no time does any memory bound to `r` leak into a return value, at least I don't see how.
> > 
> > 
> > TBH I don't know.
> 
> I note that it's only reporting one issue. Does CodeQL stop at the first issue it finds, or is that the only issue that it's found?
> 
> Thanks, Daniel

This is the only issue found.
Also, all the issues would be available in the Security tab that you can review later and dismiss if you think it isn't valid. 

This would be once the PR is merged :)

Thanks

**Pull request merged**
