### PR TITLE
fix include error in g++ 4.8

### PR DESCRIPTION
**Pull request by hongweipeng**

### CODE REVIEW

**Comment by danielaparker** [comment]
We have test coverage for gcc 4.8, but for 4.8.5. There were a lot of gcc bugs fixed between 4.8.1 and 4.8.5.

Does your code still work with gcc 4.8.2 if you change

```cpp
int_type overflow( int_type ch = std::streambuf::traits_type::eof() ) override
{
    return ch;
}
```

to 
```cpp
 int_type overflow( int_type ch = typename std::basic_streambuf<CharT>::traits_type::eof() ) override
 {
        return ch;
 }
```
?

**Comment by hongweipeng** [comment]
After the change, it can be compiled.

**Comment by hongweipeng** [comment]
Oh sorry, didn't notice that your change is different from the one in the PR. I'll try it tomorrow to see if your changes compile.

**Comment by hongweipeng** [comment]
It can be compile in gcc 4.8.2 when using `typename std::basic_streambuf<CharT>::traits_type::eof()` .

**Comment by danielaparker** [comment]
Okay, if you update your pull request to that, I'll accept it.

**Pull request merged**
